### ISSUE TITLE
search TextFormField go out when pull up

### ISSUE THREAD

**Issue by yakupbaser** [craiglabenz/flutter_pull_to_reveal#4]
hi,
there is listview on the form and i filtered one item every things okey but the search TextFormField disappears when i scroll up the list without closing the keyboard. So, only one item appears on the screen which i filtered. When I swipe up the screen after filtering, the search TextFormField shouldn't disappear when the keyboard is open.

**Comment by craiglabenz** [comment]
Great suggestion! I've just implemented this and it will go out with the next set of releases.
